Starting Celery worker with concurrency settings from config...
Worker concurrency: 3
Traceback (most recent call last):
  File "/home/xoconoch/coding/spotizerr/venv/lib/python3.13/site-packages/click_didyoumean/__init__.py", line 35, in resolve_command
    return super(DYMMixin, self).resolve_command(ctx, args)  # type: ignore
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/xoconoch/coding/spotizerr/venv/lib/python3.13/site-packages/click/core.py", line 1755, in resolve_command
    ctx.fail(_("No such command {name!r}.").format(name=original_cmd_name))
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xoconoch/coding/spotizerr/venv/lib/python3.13/site-packages/click/core.py", line 691, in fail
    raise UsageError(message, self)
click.exceptions.UsageError: No such command '/home/xoconoch/coding/venv/bin/celery'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xoconoch/coding/spotizerr/celery_worker.py", line 39, in <module>
    celery_app.worker_main()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/xoconoch/coding/spotizerr/venv/lib/python3.13/site-packages/celery/app/base.py", line 389, in worker_main
    self.start(argv=argv)
    ~~~~~~~~~~^^^^^^^^^^^
  File "/home/xoconoch/coding/spotizerr/venv/lib/python3.13/site-packages/celery/app/base.py", line 369, in start
    celery.main(args=argv, standalone_mode=False)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xoconoch/coding/spotizerr/venv/lib/python3.13/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/xoconoch/coding/spotizerr/venv/lib/python3.13/site-packages/click/core.py", line 1691, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/xoconoch/coding/spotizerr/venv/lib/python3.13/site-packages/click_didyoumean/__init__.py", line 50, in resolve_command
    raise click.exceptions.UsageError(error_msg, error.ctx)
click.exceptions.UsageError: No such command '/home/xoconoch/coding/venv/bin/celery'.
